### PR TITLE
Fixed the new UI.

### PR DESCRIPTION
**Pull request by askjag07**

### CODE REVIEW

**Comment by RishabhDevbanshi** [comment]
Please resolve merge conflicts.

**Comment by askjag07** [comment]
#69 Fixed the new UI.

Added 3D buttons with cool new UI. Hope this is good for you:
Screen Shot 2020-10-02 at 9 24 07 PM

**Comment by RishabhDevbanshi** [comment]
Reopen it.

**Comment by RishabhDevbanshi** [comment]
Resolve Merge Conflicts to merge it in master.

**Comment by askjag07** [comment]
@RishabhDevbanshi 
#72 New Pacman UI ready to hit the arcade!
Merge Conflicts resolved. Ready to merge!

**Pull request closed without merging**
