### PR TITLE
Animated the pac-man to open and close mouth

### PR DESCRIPTION
**Pull request by keithmchd48**

### CODE REVIEW

**Review by RishabhDevbanshi — APPROVED** [review]
Great Work ! Will merge soon !

**Comment by keithmchd48** [comment]
Screenshot 2020-10-04 at 2 27 15 AM
I am participating in Hackertoberfest 2020, but my PR is shown as "ineligible". Do you know the reason for this??

**Comment by RishabhDevbanshi** [comment]
> Screenshot 2020-10-04 at 2 27 15 AM
> I am participating in Hackertoberfest 2020, but my PR is shown as "ineligible". Do you know the reason for this??
> 

Maybe they changed some rules . I am not sure right now. I'll check and get back to you once I find why is it so.
Till then what you can do is open an issue regarding same so that if anyone else has idea about it, they can tell why is it so.

**Comment by keithmchd48** [comment]
Hey, Rishabh. Hacktoberfest has accepted the PR request as eligible one. Thanks a lot for your consideration!

**Comment by keithmchd48** [comment]
Hi Rishabh, I accidentally closed this PR which was approved by you. I am kind of new to open source contribution and seems like I messed up.
I have created another PR with the same changes #106.

**Pull request closed without merging**
